#!/usr/bin/env bash
# script to install and setup nginx

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# allow incoming HTTP traffic:
sudo ufw allow "Nginx HTTP"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx
sudo service nginx restart
