#!/usr/bin/env bash
# script to install and setup nginx

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# allow incoming HTTP traffic:
sudo ufw allow "Nginx HTTP"

echo "server {
    listen 80;
    server_name _;
    
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        root /var/www/html;
    }
}" | sudo tee /etc/nginx/sites-available/default


echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx
sudo service nginx restart
