#!/usr/bin/env bash
# script to install and setup nginx

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# allow incoming HTTP traffic:
sudo ufw allow "Nginx HTTP"

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

echo "server {
    listen 80;
    server_name _;
    
    location /redirect_me {
        return 301 $scheme://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;

    location / {
        root /var/www/html;
    }
}" | sudo tee /etc/nginx/sites-available/default


echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx
sudo service nginx restart
