#!/usr/bin/env bash
# Install and configure HAproxy

# Update Packages
sudo apt-get -y update
sudo apt-get -y upgrade

# Add Haproxy PPA
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.5
sudo app-get -y update

# Install Haproxy
sudo apt-get -y install haproxy=2.5.\*

# Configure Haproxy
config="\
frontend balancer
    bind *:80
    mode http
    default_backend lb-backends

backend lb-backends
    balance roundrobin
    server 175909-web-01 54.158.196.67:80 check
    server 175909-web-02 54.237.13.134:80 check
"
sudo chown -R $USER /etc/haproxy/
sudo chmod 755 /etc/haproxy/

cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo $config >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
